### ISSUE TITLE
Use MutationObserver instead of pushState listener

### ISSUE THREAD

**Issue by sindresorhus** [hzoo/github-contributor-extension#4]
https://github.com/hzoo/github-contributor-extension/blob/b41265927f1b43cd54ce182827ee20cc76008f20/src/background.js#L11-L17

You can use https://github.com/octo-linker/injection like I do in `refined-github`: https://github.com/sindresorhus/refined-github/blob/f26253482407b006d990695bc7cd6a1c43ea64de/extension/content.js#L268

**Comment by hzoo** [comment]
Wow that's great - and one less permission too!

**Comment by hzoo** [comment]
Added in next branch (Going to test for a bit) https://github.com/hzoo/github-contributor-extension/blob/bea229ea7eb59ccbbd605355725361d8523dc9af/src/content.js#L183-L189
